### ISSUE TITLE
Display the location of the building for a classroom

### ISSUE THREAD

**Issue by JeffreyJPZ** [JeffreyJPZ/ubc-classrooms#11]
As a user, I'd like to be able to see where a classroom is located so that I can decide if its too far or not.

Acceptance Criteria:
- Must display a map view that indicates the building that a classroom is in

**Comment by blucardin** [comment]
# A simpler solution
You don't need to go so far as to add coordinates of each building, just scrape the room url from the room listing here: [https://learningspaces.ubc.ca/find-space](https://learningspaces.ubc.ca/find-space)

<img width="1221" alt="Screenshot 2024-07-08 at 5 41 56 AM" src="https://github.com/JeffreyJPZ/ubc-classrooms/assets/55935207/e0de5dd5-15f7-4a02-a1ed-e9705090b9c1">

Assuming you are already scraping using selenium into a database, it shouldn't be too difficult to also store the url with the room (just add another column to the table). 

Once you have the url, just display a link to the user for every room when the user clicks the dropdown for a building. The room url displays a page with a google maps embedded window, a 360˚ view, AV setup, etc. 

<img width="1267" alt="Screenshot 2024-07-08 at 5 44 16 AM" src="https://github.com/JeffreyJPZ/ubc-classrooms/assets/55935207/01542b56-19e8-46a9-bb43-21ff935620ee">


This would give the user more information than just location, and would elevate the experience of the site above just a clone of the existing UBC database. Plus you don't even have to worry about working with location data. 

If you really wanted a direct maps integration, just copy the embedded maps iframe from a room url to the database, and embed it in the dropdown for the building. 

You could also build on top of this to add different search parameters for rooms, like capacity, furniture type, etc. 

For questions, discord: .goldensparrow

**Comment by JeffreyJPZ** [comment]
@blucardin I like the idea of using the existing room/building listings, but scraping might not even be necessary as it looks like the URLs can be generated from existing building/room names in the database ([see my PR review](https://github.com/JeffreyJPZ/ubc-classrooms/pull/20#issuecomment-2221767914)).

I will look into this at some point.
